[book]
authors = ["Owais Jamil"]
language = "en"
multilingual = false
src = "src"
title = "Lantern"

[output.html]
git-repository-url = "https://github.com/stormlightlabs/lantern"
default-theme = "coal"
preferred-dark-theme = "coal"
additional-css = ["src/assets/css/site-fonts.css"]
additional-js = ["src/assets/js/theme.js"]
